### ISSUE TITLE
ValueError: Found array with 0 sample(s) (shape=(0,)) while a minimum of 1 is required ?

### ISSUE THREAD

**Issue by HelgeCPH** [alkaline-ml/pmdarima#351]
**Question**

I have a timeline with number of some reports per week. When I try to fit a model with `auto_arima`, I receive an error `ValueError: Found array with 0 sample(s) (shape=(0,)) while a minimum of 1 is required.` (Find the complete error trace below). 

Since I am not a statistician, I do not understand what that error tells me in relation to my data. I am supposing it has something to do with seasonality given the error trace. Since the data is per week, I set `m=52`. From my programming understanding, this seems to be the reason for the error. When choosing a smaller `m` the error disappears. But I cannot really choose another `m` due to weekly data. 

In essence my question is what does `auto_arima` try to tell me here?

Even though I can see that the error originates from the `check_array` function in sklearn's `validation.py`, perhaps that exception could be caught and instead a "domain-specific" exception could be raised by `pmdarima`?

I built a small example that reproduces my issue:

```python
import pmdarima as pm
import matplotlib.pyplot as plt


week_number = ["201751", "201752", "201801", "201802", "201803", "201804", "201805", 
               "201806", "201807", "201808", "201809", "201810", "201811", "201812", 
               "201813", "201814", "201815", "201816", "201817", "201818", "201819", 
               "201820", "201821", "201822", "201823", "201824", "201825", "201826", 
               "201827", "201828", "201829", "201830", "201831", "201832", "201833", 
               "201834", "201835", "201836", "201837", "201838", "201839", "201840", 
               "201841", "201842", "201843", "201844", "201845", "201846", "201847", 
               "201848", "201849", "201850", "201851", "201852", "201853", "201900", 
               "201901", "201902", "201903", "201904", "201905", "201906", "201907", 
               "201908", "201909", "201910", "201911", "201912", "201913", "201914", 
               "201915", "201916", "201917", "201918", "201919", "201920", "201921", 
               "201922", "201923", "201924", "201925", "201926", "201927", "201928", 
               "201929", "201930", "201931", "201932"]
reports_per_week = [1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 1, 6, 2, 1, 0,
                    2, 0, 1, 0, 0, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 3, 0, 0, 6,
                    0, 0, 0, 0, 0, 1, 3, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0]


plt.plot(week_number, reports_per_week)
plt.xticks(range(0, len(week_number), 15))
plt.show()

model = pm.auto_arima(data.reports_per_week, trace=True, seasonal=True, m=52)
```

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-78-b33795e0a9d1> in <module>
     25 plt.xticks(range(0, len(week_number), 15))
     26 
---> 27 model = pm.auto_arima(data.reports_per_week, trace=True, seasonal=True, m=52)

/usr/local/anaconda3/lib/python3.7/site-packages/pmdarima/arima/auto.py in auto_arima(y, exogenous, start_p, d, start_q, max_p, max_d, max_q, start_P, D, start_Q, max_P, max_D, max_Q, max_order, m, seasonal, stationary, information_criterion, alpha, test, seasonal_test, stepwise, n_jobs, start_params, trend, method, maxiter, offset_test_args, seasonal_test_args, suppress_warnings, error_action, trace, random, random_state, n_fits, return_valid_fits, out_of_sample_size, scoring, scoring_args, with_intercept, sarimax_kwargs, **fit_args)
    398             if seasonal_test_args is not None else dict()
    399         D = nsdiffs(xx, m=m, test=seasonal_test, max_D=max_D,
--> 400                     **seasonal_test_args)
    401 
    402         if D > 0 and exogenous is not None:

/usr/local/anaconda3/lib/python3.7/site-packages/pmdarima/arima/utils.py in nsdiffs(x, m, max_D, test, **kwargs)
    108         if is_constant(x):
    109             return D
--> 110         dodiff = testfunc(x)
    111 
    112     return D

/usr/local/anaconda3/lib/python3.7/site-packages/pmdarima/arima/seasonality.py in estimate_seasonal_differencing_term(self, x)
    580 
    581         # Get the critical value for m
--> 582         stat = self._compute_test_statistic(x)
    583         crit_val = self._calc_ocsb_crit_val(self.m)
    584         return int(stat > crit_val)

/usr/local/anaconda3/lib/python3.7/site-packages/pmdarima/arima/seasonality.py in _compute_test_statistic(self, x)
    520             for lag_term in range(1, maxlag + 1):  # 1 -> maxlag (incl)
    521                 try:
--> 522                     fit = self._fit_ocsb(x, m, lag_term, maxlag)
    523                     fits.append(fit)
    524                     icvals.append(icfunc(fit))

/usr/local/anaconda3/lib/python3.7/site-packages/pmdarima/arima/seasonality.py in _fit_ocsb(x, m, lag, max_lag)
    466         """Fit the linear model used to compute the test statistic"""
    467         y_first_order_diff = diff(x, m)
--> 468         y = diff(y_first_order_diff)
    469         ylag = OCSBTest._gen_lags(y, lag)
    470 

/usr/local/anaconda3/lib/python3.7/site-packages/pmdarima/utils/array.py in diff(x, lag, differences)
    299         raise ValueError('lag and differences must be positive (> 0) integers')
    300 
--> 301     x = check_array(x, ensure_2d=False, dtype=DTYPE, copy=False)
    302     fun = _diff_vector if x.ndim == 1 else _diff_matrix
    303     res = x

/usr/local/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, warn_on_dtype, estimator)
    584                              " minimum of %d is required%s."
    585                              % (n_samples, array.shape, ensure_min_samples,
--> 586                                 context))
    587 
    588     if ensure_min_features > 0 and array.ndim == 2:

ValueError: Found array with 0 sample(s) (shape=(0,)) while a minimum of 1 is required.
```

**Versions (if necessary)**

I provide the version info just to be sure in case it becomes relevant.

```
System:
    python: 3.7.6 (default, Jan  8 2020, 13:42:34)  [Clang 4.0.1 (tags/RELEASE_401/final)]
executable: /usr/local/anaconda3/bin/python
   machine: Darwin-18.7.0-x86_64-i386-64bit

Python dependencies:
        pip: 20.0.2
 setuptools: 46.0.0.post20200309
    sklearn: 0.22.1
statsmodels: 0.11.0
      numpy: 1.18.1
      scipy: 1.4.1
     Cython: 0.29.15
     pandas: 1.0.1
     joblib: 0.14.1
   pmdarima: 1.6.1
```

Thank you for any help!

**Comment by tgsmith61591** [comment]
Hey thanks for the report. The issue is that the array quickly becomes shorter than the seasonal periodicity after a single differencing operation. I agree we should handle this on our side; if we detect this scenario, we should warn and exit at the maximum D we've successfully computed.

**Comment by tgsmith61591** [comment]
This fix has been merged into master and will be included in the 1.7.0 release

**Comment by HelgeCPH** [comment]
Hi, thank you very much for your effort and for fixing the issue! That helps - at least me - to better understand where the issue stems from.

Also thanks to all of you that created and maintain `pmdarima`! It is really useful.

**Comment by Skwal77** [comment]
thanks @tgsmith61591 !! Where can i find the new version release ( 1.7.0)? please

**Comment by tgsmith61591** [comment]
We've not released 1.7.0 yet, should be doing so very soon

**Comment by Skwal77** [comment]
Hi @tgsmith61591  i did make all the change  (#351 and #352) But i still have the same error. Can you help me?

**Comment by Skwal77** [comment]
ValueError                                Traceback (most recent call last)
c:\Users\pasca\Documents\SimWell\RPM\Projet\Prediction\ArimaPrediction.py in 
     84 
     85     # Fit your model
---> 86     model = pm.auto_arima(train , seasonal=True, m=12)
     87 
     88     # make your forecasts

~\AppData\Local\Programs\Python\Python38\lib\site-packages\pmdarima\arima\auto.py in auto_arima(y, exogenous, start_p, d, start_q, max_p, max_d, max_q, start_P, D, start_Q, max_P, max_D, max_Q, max_order, m, seasonal, stationary, information_criterion, alpha, test, seasonal_test, stepwise, n_jobs, start_params, trend, method, maxiter, offset_test_args, seasonal_test_args, suppress_warnings, error_action, trace, random, random_state, n_fits, return_valid_fits, out_of_sample_size, scoring, scoring_args, with_intercept, sarimax_kwargs, **fit_args)
    397         seasonal_test_args = seasonal_test_args \
    398             if seasonal_test_args is not None else dict()
--> 399         print("Change works!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
    400         D = nsdiffs(xx, m=m, test=seasonal_test, max_D=max_D,
    401                     **seasonal_test_args)

~\AppData\Local\Programs\Python\Python38\lib\site-packages\pmdarima\arima\utils.py in nsdiffs(x, m, max_D, test, **kwargs)
    127                           % (len(x), m, D))
    128             return D
--> 129         dodiff = testfunc(x)
    130 
    131     return D

~\AppData\Local\Programs\Python\Python38\lib\site-packages\pmdarima\arima\seasonality.py in estimate_seasonal_differencing_term(self, x)
    580 
    581         # Get the critical value for m
--> 582         stat = self._compute_test_statistic(x)
    583         crit_val = self._calc_ocsb_crit_val(self.m)
    584         return int(stat > crit_val)

~\AppData\Local\Programs\Python\Python38\lib\site-packages\pmdarima\arima\seasonality.py in _compute_test_statistic(self, x)
    520             for lag_term in range(1, maxlag + 1):  # 1 -> maxlag (incl)
    521                 try:
--> 522                     fit = self._fit_ocsb(x, m, lag_term, maxlag)
    523                     fits.append(fit)
    524                     icvals.append(icfunc(fit))

~\AppData\Local\Programs\Python\Python38\lib\site-packages\pmdarima\arima\seasonality.py in _fit_ocsb(x, m, lag, max_lag)
    466         """Fit the linear model used to compute the test statistic"""
    467         y_first_order_diff = diff(x, m)
--> 468         y = diff(y_first_order_diff)
    469         ylag = OCSBTest._gen_lags(y, lag)
    470 

~\AppData\Local\Programs\Python\Python38\lib\site-packages\pmdarima\utils\array.py in diff(x, lag, differences)
    299         raise ValueError('lag and differences must be positive (> 0) integers')
    300 
--> 301     x = check_array(x, ensure_2d=False, dtype=DTYPE, copy=False)
    302     fun = _diff_vector if x.ndim == 1 else _diff_matrix
    303     res = x

~\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\utils\validation.py in inner_f(*args, **kwargs)
     71                           FutureWarning)
     72         kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
---> 73         return f(**kwargs)
     74     return inner_f
     75 

~\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\utils\validation.py in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, estimator)
    649         n_samples = _num_samples(array)
    650         if n_samples < ensure_min_samples:
--> 651             raise ValueError("Found array with %d sample(s) (shape=%s) while a"
    652                              " minimum of %d is required%s."
    653                              % (n_samples, array.shape, ensure_min_samples,

ValueError: Found array with 0 sample(s) (shape=(0,)) while a minimum of 1 is required.

**Comment by Skwal77** [comment]
ValueError                                Traceback (most recent call last)
c:\Users\pasca\Documents\SimWell\RPM\Projet\Prediction\ArimaPrediction.py in 
     84 
     85     # Fit your model
---> 86     model = pm.auto_arima(train , seasonal=True, m=12)
     87 
     88     # make your forecasts

~\AppData\Local\Programs\Python\Python38\lib\site-packages\pmdarima\arima\auto.py in auto_arima(y, exogenous, start_p, d, start_q, max_p, max_d, max_q, start_P, D, start_Q, max_P, max_D, max_Q, max_order, m, seasonal, stationary, information_criterion, alpha, test, seasonal_test, stepwise, n_jobs, start_params, trend, method, maxiter, offset_test_args, seasonal_test_args, suppress_warnings, error_action, trace, random, random_state, n_fits, return_valid_fits, out_of_sample_size, scoring, scoring_args, with_intercept, sarimax_kwargs, **fit_args)
    397         seasonal_test_args = seasonal_test_args \
    398             if seasonal_test_args is not None else dict()
--> 399         D = nsdiffs(xx, m=m, test=seasonal_test, max_D=max_D,
    400                     **seasonal_test_args)
    401 

~\AppData\Local\Programs\Python\Python38\lib\site-packages\pmdarima\arima\utils.py in nsdiffs(x, m, max_D, test, **kwargs)
    127                           % (len(x), m, D))
    128             return D
--> 129         dodiff = testfunc(x)
    130 
    131     return D

~\AppData\Local\Programs\Python\Python38\lib\site-packages\pmdarima\arima\seasonality.py in estimate_seasonal_differencing_term(self, x)
    580 
    581         # Get the critical value for m
--> 582         stat = self._compute_test_statistic(x)
    583         crit_val = self._calc_ocsb_crit_val(self.m)
    584         return int(stat > crit_val)

~\AppData\Local\Programs\Python\Python38\lib\site-packages\pmdarima\arima\seasonality.py in _compute_test_statistic(self, x)
    520             for lag_term in range(1, maxlag + 1):  # 1 -> maxlag (incl)
    521                 try:
--> 522                     fit = self._fit_ocsb(x, m, lag_term, maxlag)
    523                     fits.append(fit)
    524                     icvals.append(icfunc(fit))

~\AppData\Local\Programs\Python\Python38\lib\site-packages\pmdarima\arima\seasonality.py in _fit_ocsb(x, m, lag, max_lag)
    466         """Fit the linear model used to compute the test statistic"""
    467         y_first_order_diff = diff(x, m)
--> 468         y = diff(y_first_order_diff)
    469         ylag = OCSBTest._gen_lags(y, lag)
    470 

~\AppData\Local\Programs\Python\Python38\lib\site-packages\pmdarima\utils\array.py in diff(x, lag, differences)
    299         raise ValueError('lag and differences must be positive (> 0) integers')
    300 
--> 301     x = check_array(x, ensure_2d=False, dtype=DTYPE, copy=False)
    302     fun = _diff_vector if x.ndim == 1 else _diff_matrix
    303     res = x

~\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\utils\validation.py in inner_f(*args, **kwargs)
     71                           FutureWarning)
     72         kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
---> 73         return f(**kwargs)
     74     return inner_f
     75 

~\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\utils\validation.py in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, estimator)
    649         n_samples = _num_samples(array)
    650         if n_samples < ensure_min_samples:
--> 651             raise ValueError("Found array with %d sample(s) (shape=%s) while a"
    652                              " minimum of %d is required%s."
    653                              % (n_samples, array.shape, ensure_min_samples,

ValueError: Found array with 0 sample(s) (shape=(0,)) while a minimum of 1 is required.

**Comment by tgsmith61591** [comment]
Please provide your data and share how you built the package

**Comment by Skwal77** [comment]
![image](https://user-images.githubusercontent.com/68301613/88931485-e46d4280-d24a-11ea-86ea-7e1429769a51.png)

**Comment by Skwal77** [comment]
![image](https://user-images.githubusercontent.com/68301613/88931561-fbac3000-d24a-11ea-89ae-8fe1cac80857.png)

**Comment by tgsmith61591** [comment]
Don't take a screenshot, please paste code/attach files. It's difficult to copy/paste code from a screen shot!

**Comment by Skwal77** [comment]
# %%
import pmdarima as pm
from pmdarima.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt
horizon = 24
for i in range(24,26):
    # Load/split your data
    y = FichierConcatW[:, i]
    train, test = train_test_split(y, train_size=horizon)

    # Fit your model
    model = pm.auto_arima(train , seasonal=True, m=12)

    # make your forecasts
    forecasts = model.predict(test.shape[0])  # predict N steps into the future

    # Visualize the forecasts (blue=train, green=forecasts)
    x = np.arange(y.shape[0])
    plt.plot(x[:horizon], train, c='blue')
    plt.plot(x[horizon:], forecasts, c='green')
    plt.plot(x[horizon:], test, c='black')
    plt.show()

**Comment by tgsmith61591** [comment]
I still need your data and how you built the package.

>  i did make all the change (#351 and #352) But i still have the same error

How did you include those changes? Or are you using a pypi dist?

**Comment by Skwal77** [comment]
[fichierConcat.txt](https://github.com/alkaline-ml/pmdarima/files/5001665/fichierConcat.txt)

**Comment by Skwal77** [comment]
I make all the changes manually in each .py file. Sorry for my explanation, I'm new to python.

**Comment by Skwal77** [comment]
the code work for the range  24:26 but it'snot working for 24:30

**Comment by Skwal77** [comment]
But i need it to work from 0 to 1205,

**Comment by tgsmith61591** [comment]
There are no more samples after a first-order seasonal differencing operation in the OCSB test. That usually occurs when the seasonal stationarity test detects it should perform differencing (`D`) but the combination of a high `m` and a low `n_samples` results in an empty array after differencing. You have two options as work-arounds:

* use a larger training set
* manually set `D=0` in the `auto_arima` call.

**Comment by Skwal77** [comment]
Thank you so much @tgsmith61591

**Comment by Skwal77** [comment]
@tgsmith61591 Sorry to bother you. But I'd like to know how I can use multiprocessing with this code. Can you help me? I took a different approach. but nothing wrok.

**Comment by Skwal77** [comment]
import time
from timeit import default_timer as timer
from multiprocessing import Pool, cpu_count

def sum_up_to(i):
    for d in  range (horizon, 25):
        # Load/split your data
        y = FichierConcatW[:, i]
        train, test = train_test_split(y, train_size=d)

        # Fit your model
        model = pm.auto_arima(train , seasonal=True, m=12, D=0)

        # make your forecasts
        forecasts = model.predict(test.shape[0])  # predict N steps into the future
        # Rempalce valeur  prédide dans le tableau
        FichierConcatPredic[d,i]=forecasts[0]
        #print(forecasts[0])
        print(d)
        print(i)

        # Visualize the forecasts (blue=train, green=forecasts)
        #x = np.arange(y.shape[0])
        #plt.plot(x[:d], train, c='blue')
        #plt.plot(x[d:], forecasts, c='green')
        #plt.plot(x[d:], test, c='black')
        #plt.show()

def main():

    start = timer()

    print(f'starting computations on {cpu_count()} cores')

    values = range(0,10)

    with Pool() as pool:
        res = pool.map(sum_up_to, values)
        print(res)

    end = timer()
    print(f'elapsed time: {end - start}')

if __name__ == '__main__':
    main()   




# %%
import warnings
import pmdarima as pm
from pmdarima.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt
from timeit import default_timer as timer
import multiprocessing
import concurrent.futures

warnings.filterwarnings('ignore')
start = timer()
horizon = 24
def sum_up_to(i):
    for d in  range (horizon, 25):
        # Load/split your data
        y = FichierConcatW[:, i]
        train, test = train_test_split(y, train_size=d)

        # Fit your model
        model = pm.auto_arima(train , seasonal=True, m=12, D=0)

        # make your forecasts
        forecasts = model.predict(test.shape[0])  # predict N steps into the future
        # Rempalce valeur  prédide dans le tableau
        FichierConcatPredic[d,i]=forecasts[0]
        #print(forecasts[0])
        print(d)
        print(i)

        # Visualize the forecasts (blue=train, green=forecasts)
        #x = np.arange(y.shape[0])
        #plt.plot(x[:d], train, c='blue')
        #plt.plot(x[d:], forecasts, c='green')
        #plt.plot(x[d:], test, c='black')
        #plt.show()
        return i


with concurrent.futures.ProcessPoolExecutor() as executor:
    results = [executor.submit(sum_up_to, position) for position in range(0,10)]
    for f in concurrent.futures.as_completed(results):
        print(f.result())


end = timer()
print(f'elapsed time: {end - start}')

**Comment by Skwal77** [comment]
`import time
from timeit import default_timer as timer
from multiprocessing import Pool, cpu_count
horizon = 24
def sum_up_to(i):
    for d in  range (horizon, 25):
        # Load/split your data
        y = FichierConcatW[:, i]
        train, test = train_test_split(y, train_size=d)

        # Fit your model
        model = pm.auto_arima(train , seasonal=True, m=12, D=0)

        # make your forecasts
        forecasts = model.predict(test.shape[0])  # predict N steps into the future
        # Rempalce valeur  prédide dans le tableau
        FichierConcatPredic[d,i]=forecasts[0]
        #print(forecasts[0])
        print(d)
        print(i)

        # Visualize the forecasts (blue=train, green=forecasts)
        #x = np.arange(y.shape[0])
        #plt.plot(x[:d], train, c='blue')
        #plt.plot(x[d:], forecasts, c='green')
        #plt.plot(x[d:], test, c='black')
        #plt.show()

def main():

    start = timer()

    print(f'starting computations on {cpu_count()} cores')

    values = range(0,10)

    with Pool() as pool:
        res = pool.map(sum_up_to, values)
        print(res)

    end = timer()
    print(f'elapsed time: {end - start}')

if __name__ == '__main__':
    main()   
`

**Comment by Skwal77** [comment]
`import warnings
import pmdarima as pm
from pmdarima.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt
from timeit import default_timer as timer
import multiprocessing
import concurrent.futures

warnings.filterwarnings('ignore')
start = timer()
horizon = 24
def sum_up_to(i):
    for d in  range (horizon, 25):
        # Load/split your data
        y = FichierConcatW[:, i]
        train, test = train_test_split(y, train_size=d)

        # Fit your model
        model = pm.auto_arima(train , seasonal=True, m=12, D=0)

        # make your forecasts
        forecasts = model.predict(test.shape[0])  # predict N steps into the future
        # Rempalce valeur  prédide dans le tableau
        FichierConcatPredic[d,i]=forecasts[0]
        #print(forecasts[0])
        print(d)
        print(i)

        # Visualize the forecasts (blue=train, green=forecasts)
        #x = np.arange(y.shape[0])
        #plt.plot(x[:d], train, c='blue')
        #plt.plot(x[d:], forecasts, c='green')
        #plt.plot(x[d:], test, c='black')
        #plt.show()
        return i


with concurrent.futures.ProcessPoolExecutor() as executor:
    results = [executor.submit(sum_up_to, position) for position in range(0,10)]
    for f in concurrent.futures.as_completed(results):
        print(f.result())


end = timer()
print(f'elapsed time: {end - start}')`

**Comment by eshwar1992** [comment]
I am getting following error,
ValueError: Found array with 0 sample(s) (shape=(0,)) while a minimum of 1 is required.

for s in training['customer'].unique():
    print(s)
    for c in training['category'].unique():
        print(c)
        endog = training.loc[(training['customer'] == s) & (training['category'] == c), 'transaction_amount']
        exog = training.loc[(training['customer'] == s) & (training['category'] == c)].drop(['customer', 'category', 'transaction_amount'], axis=1)
        arimax = pmdarima.arima.auto_arima(endog, exogenous=exog,
                               start_p=0, d=0, start_q=0,
                               test='adf',
                               max_p=2, max_d=2, max_q=2, start_P=0, D=None, start_Q=0, m=12,
                               max_P=2, max_D=2, max_Q=2, seasonal=True, trace=True,
                               error_action='trace',  
                               suppress_warnings=True, 
                               stepwise=True)
        exog_test = df_test_ex.loc[(df_test_ex['customer'] == s) & (df_test_ex['category'] == c)].drop(['customer', 'category', 'transaction_amount'], axis=1)
        n_periods = 180
        fitted, confint = arimax.predict(n_periods=n_periods, 
                                      exogenous=exog_test, 
                                      return_conf_int=True)
        #fitted_series = pd.Series(fitted)
        empty = df_test.loc[(df_test['customer'] == s) & (df_test['category'] == c)]
        empty['transaction_amount'] = fitted
        empty['transaction_amount'][empty['transaction_amount'] < 0] = 0
        temp = pd.concat([empty, temp])

**Comment by tgsmith61591** [comment]
@eshwar1992 there's nothing we can really do to help given the (unformatted) code you've posted. We will need to have a sample of your data to understand why things are going awry. Please fix the formatting and attach a sample of data.
